// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUuH8TtF6PVW4cMZlnnWwB-pvagSCkFs',
    appId: '1:139306597357:android:f84b9f908b234724cc85e4',
    messagingSenderId: '139306597357',
    projectId: 'tomb-raider-e178e',
    databaseURL: 'https://tomb-raider-e178e.firebaseio.com',
    storageBucket: 'tomb-raider-e178e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Nwd0Mf58vOEFQf9HqNdquRvv6556FNU',
    appId: '1:139306597357:ios:917751361e1d52bdcc85e4',
    messagingSenderId: '139306597357',
    projectId: 'tomb-raider-e178e',
    databaseURL: 'https://tomb-raider-e178e.firebaseio.com',
    storageBucket: 'tomb-raider-e178e.appspot.com',
    iosClientId: '139306597357-revdc24iduloecrotjavlk5594kkn24q.apps.googleusercontent.com',
    iosBundleId: 'com.anisdev.learningApp',
  );
}
